package org.example.dao;

import org.example.DBUtil;
import org.example.model.Clothing;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static org.example.model.Clothing.create;

public class ClothingDAO {
    // SQL query to retrieve all clothing records
    private static final String GET_ALL_SQL = "SELECT category, prodName, quantity, unitCost, margin, volume FROM clothing";
    // SQL insert statement for clothing (sku is auto-generated by the database)
    private static final String INSERT_ELECTRONICS_SQL = "insert into clothing(category, prodName, quantity, unitCost, margin, volume) values (?, ?, ?, ?, ?, ?)";

    public void batchInsertClothing(List<Clothing> clothingCSVList) throws SQLException {
        // Use try-with-resources to ensure connection and statement are closed
        try(Connection conn = DBUtil.getConnection();
            PreparedStatement ps = conn.prepareStatement(INSERT_ELECTRONICS_SQL)){
            conn.setAutoCommit(false);      // Disable auto-commit to manage transaction manually

            // Loop through each product and add its parameters to the batch
            for (Clothing c : clothingCSVList) {
                ps.setString(1, c.getCategory());
                ps.setString(2, c.getProdName());
                ps.setInt(3, c.getQuantity());
                ps.setDouble(4, c.getUnitCost());
                ps.setInt(5, c.getMargin());
                ps.setDouble(6, c.getVolume());
                ps.addBatch();
            }

            ps.executeBatch();      // Execute the entire batch
            conn.commit();          // Commit the transaction
        } catch (SQLException e) {
            throw e;
        }
    }

    public List<Clothing> getAllClothing() {
        List<Clothing> list = new ArrayList<>();
        // Use try-with-resources to manage connection, statement, and result set
        try (Connection conn = DBUtil.getConnection();
             PreparedStatement ps = conn.prepareStatement(GET_ALL_SQL);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {     // Iterate through result set
                // Use the factory method to create a clothing object (validates data)
                Optional<Clothing> clothOpt = create(
                        rs.getString("category"),
                        rs.getString("prodName"),
                        rs.getInt("quantity"),
                        rs.getDouble("unitCost"),
                        rs.getInt("margin"),
                        rs.getDouble("volume"));
                // Add to list only if object is valid
                clothOpt.ifPresent(list::add);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }
}
