package org.example.dao;

import org.example.DBUtil;
import org.example.model.Electronics;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static org.example.model.Electronics.create;

public class ElectronicsDAO {
    // SQL query to retrieve all electronics records
    private static final String GET_ALL_SQL = "SELECT category, prodName, quantity, unitCost, margin, weight FROM electronics";
    // SQL insert statement for electronics (sku is auto-generated by the database)
    private static final String INSERT_ELECTRONICS_SQL = "insert into electronics(category, prodName, quantity, unitCost, margin, weight) values (?, ?, ?, ?, ?, ?)";

    public void batchInsertElectronics(List<Electronics> electronicsList) throws SQLException {
        // Use try-with-resources to ensure connection and statement are closed
        try(Connection conn = DBUtil.getConnection();
            PreparedStatement ps = conn.prepareStatement(INSERT_ELECTRONICS_SQL)){
            conn.setAutoCommit(false);      // Disable auto-commit to manage transaction manually

            // Loop through each product and add its parameters to the batch
            for (Electronics e : electronicsList) {
                ps.setString(1, e.getCategory());
                ps.setString(2, e.getProdName());
                ps.setInt(3, e.getQuantity());
                ps.setDouble(4, e.getUnitCost());
                ps.setInt(5, e.getMargin());
                ps.setDouble(6, e.getWeight());
                ps.addBatch();
            }

            ps.executeBatch();      // Execute the entire batch
            conn.commit();          // Commit the transaction
        } catch (SQLException e) {
            throw e;
        }
    }

    public List<Electronics> getAllElectronics() {
        List<Electronics> list = new ArrayList<>();
        // Use try-with-resources to manage connection, statement, and result set
        try (Connection conn = DBUtil.getConnection();
             PreparedStatement ps = conn.prepareStatement(GET_ALL_SQL);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {     // Iterate through result set
                // Use the factory method to create an Electronics object (validates data)
                Optional<Electronics> electroOpt = create(
                        rs.getString("category"),
                        rs.getString("prodName"),
                        rs.getInt("quantity"),
                        rs.getDouble("unitCost"),
                        rs.getInt("margin"),
                        rs.getDouble("weight"));
                // Add to list only if object is valid
                electroOpt.ifPresent(list::add);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }
}
